export class GameHud {
  constructor(container, actions) {
    this.coordinatesVisible = true; this.element = document.createElement("aside"); this.element.className = "hud";
    this.element.innerHTML = `<h1>Cube Chess 512 <span>AI</span></h1><dl><dt>Active level</dt><dd data-level>A</dd><dt>Visible levels</dt><dd data-visible-levels>8</dd><dt>Visible squares</dt><dd data-visible-squares>512</dd><dt>Total cube squares</dt><dd>512</dd><dt>Selected square</dt><dd data-square>None</dd><dt>Selected piece</dt><dd data-piece>None</dd></dl><div class="level-buttons" data-levels>${"ABCDEFGH".split("").map((name, index) => `<button data-level="${index}">${name}</button>`).join("")}</div><p>Rendering stage — movement disabled</p><div class="hud-actions"><button data-previous>Previous Level</button><button data-next>Next Level</button><button data-all>Show All Levels</button><button data-isolate>Isolate Active Level</button><button data-cube>Cube View</button><button data-active>Active Layer View</button><button data-reset>Reset Camera</button><button data-coordinates>Hide Coordinates</button></div>`;
    container.append(this.element); this.element.querySelector("[data-reset]").addEventListener("click", actions.reset); ["previous", "next", "all", "isolate", "cube", "active"].forEach((name) => this.element.querySelector(`[data-${name}]`).addEventListener("click", actions[name])); this.element.querySelectorAll("[data-level]").forEach((button) => button.addEventListener("click", () => actions.level(Number(button.dataset.level)))); this.coordinateButton = this.element.querySelector("[data-coordinates]"); this.coordinateButton.addEventListener("click", () => { this.coordinatesVisible = !this.coordinatesVisible; actions.toggleCoordinates(this.coordinatesVisible); this.coordinateButton.textContent = this.coordinatesVisible ? "Hide Coordinates" : "Show Coordinates"; });
  }
  update(state) { this.element.querySelector("[data-square]").textContent = state.selectedSquare?.square3D ?? "None"; this.element.querySelector("[data-piece]").textContent = state.selectedPieceId ?? "None"; this.element.querySelector("[data-level]").textContent = state.levels[state.activeLevel].name; const count = state.levels.filter((level) => level.visible).length; this.element.querySelector("[data-visible-levels]").textContent = count; this.element.querySelector("[data-visible-squares]").textContent = count * 64; this.element.querySelectorAll(".level-buttons button").forEach((button) => button.classList.toggle("active", Number(button.dataset.level) === state.activeLevel)); }
  dispose() { this.element.remove(); }
}
