const STORAGE_KEY = "cubeChessTutorial";
const STORAGE_VERSION = 3;
const LEVEL_NAMES = "ABCDEFGH";

const COPY = {
  en: {
    title: "3D tutorial",
    close: "Hide instructions",
    previous: "Back",
    next: "Next",
    why: "Why?",
    repeat: "Show on board",
    auto: "Explain every move",
    progress: "Step {current} of {total}",
    boardTitle: "Eight boards form one cube",
    board: "Watch the existing 3D board. The camera will show levels A–H: eight boards × 64 squares = 512 fields.",
    selectTitle: "Choose a white piece",
    select: "Select a white piece directly on the 3D model. The engine will highlight every legal destination on all levels.",
    selectedTitle: "Read the highlights",
    selected: "Highlighted targets are generated by the real move engine. Targets above or below the piece are spatial moves.",
    dimensionTitle: "Move through height",
    dimension: "The classical movement shape is preserved and extended into height. Use a highlighted field on another level.",
    completeTitle: "Core rule understood",
    complete: "Length, width and height are equal axes. The rules are not replaced; their geometry is extended to 3D.",
    pawnPromotionTitle: "6. Pawn Promotion in 3D Space",
    pawnPromotion: "On Levels 1 through 7, a pawn may be promoted according to the classical chess rule. If it reaches the opponent’s final rank on its current level, the player may replace it with a queen, rook, bishop or knight.\n\nA pawn may also advance vertically between levels. If a legal move places it on Level 8, it is promoted immediately, regardless of the rank, file or square on which it entered the highest level.\n\nDuring promotion, the available pieces are highlighted in yellow. A pawn cannot be promoted to a king or another pawn.",
    legalSame: "Legal move on the same level.",
    legalSpatial: "Legal spatial move from level {from} to level {to}.",
    capture: "Legal capture on level {to}.",
    whiteOnly: "Choose a white piece to continue.",
    noMoves: "Choose a piece on the 3D board first.",
    rook: "The rook follows one straight axis, including vertically between levels, and cannot jump.",
    bishop: "The bishop follows diagonals that may also change level.",
    queen: "The queen combines rook and bishop geometry in three dimensions.",
    king: "The king takes one legal step in any engine-approved 3D direction.",
    knight: "The knight changes two cells on one axis and one on another; height can be either axis.",
    pawn: "Pawn movement and captures are shown only from the engine's current legal targets.",
    generic: "This piece keeps its classical geometry and extends it into height.",
  },
  pl: {
    title: "Samouczek 3D",
    close: "Ukryj instrukcję",
    previous: "Wstecz",
    next: "Dalej",
    why: "Dlaczego?",
    repeat: "Pokaż na planszy",
    auto: "Wyjaśniaj każdy ruch",
    progress: "Krok {current} z {total}",
    boardTitle: "Osiem plansz tworzy jeden sześcian",
    board: "Obserwuj istniejący model 3D. Kamera pokaże poziomy A–H: osiem plansz × 64 pola = 512 pól.",
    selectTitle: "Wybierz białą figurę",
    select: "Wybierz białą figurę bezpośrednio na modelu 3D. Silnik podświetli wszystkie legalne cele na każdym poziomie.",
    selectedTitle: "Odczytaj podświetlenia",
    selected: "Podświetlone cele pochodzą z prawdziwego silnika ruchów. Cele nad lub pod figurą są ruchami przestrzennymi.",
    dimensionTitle: "Wykonaj ruch przez wysokość",
    dimension: "Klasyczny kształt ruchu pozostaje bez zmian i zostaje rozszerzony o wysokość. Wybierz podświetlone pole na innym poziomie.",
    completeTitle: "Główna zasada zrozumiana",
    complete: "Długość, szerokość i wysokość są równorzędnymi osiami. Reguły nie są zastępowane, tylko rozszerzone do 3D.",
    pawnPromotionTitle: "6. Promocja pionka w przestrzeni 3D",
    pawnPromotion: "Na poziomach od 1 do 7 pionek może zostać promowany zgodnie z klasyczną zasadą szachową. Jeżeli dotrze do ostatniego rzędu przeciwnika na swoim aktualnym poziomie, gracz może zamienić go na hetmana, wieżę, gońca albo skoczka.\n\nPionek może również awansować pionowo pomiędzy poziomami. Jeżeli po legalnym ruchu wejdzie na poziom 8, zostaje promowany natychmiast, niezależnie od rzędu, kolumny i pola, na którym znalazł się na najwyższym poziomie.\n\nPodczas promocji dostępne figury zostaną podświetlone na żółto. Nie można promować pionka na króla ani na kolejnego pionka.",
    legalSame: "Legalny ruch na tym samym poziomie.",
    legalSpatial: "Legalny ruch przestrzenny z poziomu {from} na poziom {to}.",
    capture: "Legalne bicie na poziomie {to}.",
    whiteOnly: "Wybierz białą figurę, aby kontynuować.",
    noMoves: "Najpierw wybierz figurę na planszy 3D.",
    rook: "Wieża porusza się wzdłuż jednej prostej osi, także pionowo między poziomami, i nie może przeskakiwać.",
    bishop: "Goniec porusza się po przekątnych, które mogą również zmieniać poziom.",
    queen: "Królowa łączy geometrię wieży i gońca w trzech wymiarach.",
    king: "Król wykonuje jeden legalny krok w dowolnym kierunku 3D dopuszczonym przez silnik.",
    knight: "Skoczek zmienia pozycję o dwa pola w jednej osi i jedno w drugiej; wysokość może być jedną z tych osi.",
    pawn: "Ruchy i bicia pionka są pokazywane wyłącznie na podstawie aktualnych legalnych celów silnika.",
    generic: "Figura zachowuje klasyczną geometrię i rozszerza ją o wysokość.",
  },
};

export const STEPS = [
  ["boardTitle", "board"],
  ["selectTitle", "select"],
  ["selectedTitle", "selected"],
  ["dimensionTitle", "dimension"],
  ["completeTitle", "complete"],
  ["pawnPromotionTitle", "pawnPromotion"],
];

function interpolate(text, values = {}) {
  return text.replace(/\{(\w+)\}/g, (_, key) => String(values[key] ?? ""));
}

export function loadTutorialProgress(storage = globalThis.localStorage) {
  const fallback = { version: STORAGE_VERSION, step: 0, complete: false, autoExplain: true };
  try {
    const value = JSON.parse(storage?.getItem(STORAGE_KEY) || "null");
    if (!value || ![1, 2, STORAGE_VERSION].includes(value.version)) return fallback;
    return {
      ...fallback,
      autoExplain: value.autoExplain !== false,
      complete: Boolean(value.complete),
      step: Math.max(0, Math.min(STEPS.length - 1, Number(value.step) || 0)),
    };
  } catch {
    return fallback;
  }
}

export function classifyMove(move) {
  if (!move?.from || !move?.to) return "unknown";
  if (move.capturedPieceId || move.kind === "capture") return "capture";
  return move.from.z === move.to.z ? "same-level" : "spatial";
}

export function pieceExplanationKey(piece) {
  const type = String(piece?.type || piece?.kind || "").toLowerCase();
  return ["rook", "bishop", "queen", "king", "knight", "pawn"].includes(type) ? type : "generic";
}

export class TutorialController {
  constructor(root, application) {
    this.root = root;
    this.application = application;
    this.progress = loadTutorialProgress();
    this.lastSequence = 0;
    this.lastSelectedPieceId = null;
    this.active = false;
    this.hiddenByPlayer = false;
    this.levelTourTimer = null;
    this.createUi();
    this.render(application.presentation.snapshot());
  }

  t(key, values) {
    const language = this.application.presentation.language === "pl" ? "pl" : "en";
    return interpolate(COPY[language][key] || COPY.en[key] || key, values);
  }

  createUi() {
    this.panel = document.createElement("aside");
    this.panel.className = "tutorial-panel";
    this.panel.hidden = true;
    this.panel.setAttribute("aria-live", "polite");
    this.panel.innerHTML = `
      <div class="tutorial-header"><strong data-role="title"></strong><button type="button" data-action="close" aria-label="Close">×</button></div>
      <div class="tutorial-progress" data-role="progress"></div>
      <h2 data-role="step-title"></h2>
      <p data-role="message"></p>
      <p class="tutorial-explanation" data-role="explanation"></p>
      <label class="tutorial-toggle"><input type="checkbox" data-action="auto"> <span data-role="auto-label"></span></label>
      <div class="tutorial-actions">
        <button type="button" data-action="previous"></button>
        <button type="button" data-action="next"></button>
        <button type="button" data-action="why"></button>
        <button type="button" data-action="repeat"></button>
      </div>`;
    this.panel.addEventListener("click", (event) => this.handleAction(event));
    this.panel.querySelector('[data-action="auto"]').addEventListener("change", (event) => {
      this.progress.autoExplain = event.target.checked;
      this.save();
    });
    this.root.append(this.panel);
  }

  isTutorialState(state) {
    return state?.gameConfig?.mode === "tutorial" && state.appState === "playing" && !state.menuOpen;
  }

  leaveTutorialView() {
    window.clearInterval(this.levelTourTimer);
    this.levelTourTimer = null;
    this.panel.hidden = true;
    this.hiddenByPlayer = false;
    this.dynamicMessage = "";
    this.lastSelectedPieceId = null;
    this.application.renderer.showAllLevels();
    this.application.renderer.setActiveLevel(0);
    this.application.renderer.cubeView();
  }

  handleAction(event) {
    const action = event.target.closest("[data-action]")?.dataset.action;
    if (!action) return;
    if (action === "close") this.hiddenByPlayer = true;
    if (action === "previous") this.progress.step = Math.max(0, this.progress.step - 1);
    if (action === "next") this.progress.step = Math.min(STEPS.length - 1, this.progress.step + 1);
    if (action === "why" && this.progress.step < STEPS.length - 1) this.showPieceExplanation();
    if (action === "repeat" && this.progress.step < STEPS.length - 1) this.demonstrateCurrentStep();
    this.save();
    this.render();
  }

  save() {
    try { localStorage.setItem(STORAGE_KEY, JSON.stringify(this.progress)); } catch { /* optional */ }
  }

  showPieceExplanation() {
    const state = this.application.presentation.snapshot();
    const piece = state.pieces.find((candidate) => candidate.id === state.selectedPieceId);
    this.dynamicMessage = this.t(pieceExplanationKey(piece));
  }

  demonstrateCurrentStep() {
    if (this.progress.step === 0) this.startLevelTour();
    else {
      const state = this.application.presentation.snapshot();
      if (state.selectedPieceId) this.application.renderer.refresh();
      else this.dynamicMessage = this.t("noMoves");
    }
  }

  startLevelTour() {
    window.clearInterval(this.levelTourTimer);
    this.application.renderer.showAllLevels();
    this.application.renderer.cubeView();
    let level = 0;
    this.application.renderer.setActiveLevel(level);
    this.levelTourTimer = window.setInterval(() => {
      level += 1;
      if (level >= 8 || !this.active) {
        window.clearInterval(this.levelTourTimer);
        this.levelTourTimer = null;
        this.application.renderer.showAllLevels();
        this.application.renderer.cubeView();
        return;
      }
      this.application.renderer.setActiveLevel(level);
    }, document.documentElement.classList.contains("reduce-motion") ? 80 : 450);
  }

  onStateChange(state) {
    const wasActive = this.active;
    this.active = this.isTutorialState(state);
    if (!this.active) {
      if (wasActive) this.leaveTutorialView();
      else this.panel.hidden = true;
      return;
    }

    if (!wasActive) {
      this.hiddenByPlayer = false;
      this.progress.step = 0;
      this.dynamicMessage = "";
      queueMicrotask(() => this.startLevelTour());
    }

    if (state.selectedPieceId && state.selectedPieceId !== this.lastSelectedPieceId) {
      const piece = state.pieces.find((candidate) => candidate.id === state.selectedPieceId);
      if (piece?.color !== "white") this.dynamicMessage = this.t("whiteOnly");
      else {
        this.progress.step = Math.max(this.progress.step, 2);
        this.dynamicMessage = this.t(pieceExplanationKey(piece));
      }
      this.lastSelectedPieceId = state.selectedPieceId;
    }

    if (state.lastMove?.sequence && state.lastMove.sequence !== this.lastSequence) {
      this.lastSequence = state.lastMove.sequence;
      const kind = classifyMove(state.lastMove);
      const from = LEVEL_NAMES[state.lastMove.from?.z ?? 0];
      const to = LEVEL_NAMES[state.lastMove.to?.z ?? 0];
      this.dynamicMessage = kind === "capture"
        ? this.t("capture", { to })
        : kind === "spatial"
          ? this.t("legalSpatial", { from, to })
          : this.t("legalSame");
      this.progress.step = kind === "spatial" ? 4 : Math.max(this.progress.step, 3);
      this.progress.complete = kind === "spatial";
      if (this.progress.autoExplain) this.hiddenByPlayer = false;
    }

    this.save();
    this.render(state);
  }

  render(state = this.application.presentation.snapshot()) {
    this.active = this.isTutorialState(state);
    this.panel.hidden = !this.active || this.hiddenByPlayer;
    if (this.panel.hidden) return;

    const [titleKey, messageKey] = STEPS[this.progress.step];
    const promotionStep = this.progress.step === STEPS.length - 1;
    const message = this.panel.querySelector('[data-role="message"]');
    this.panel.querySelector('[data-role="title"]').textContent = this.t("title");
    this.panel.querySelector('[data-role="progress"]').textContent = this.t("progress", { current: this.progress.step + 1, total: STEPS.length });
    this.panel.querySelector('[data-role="step-title"]').textContent = this.t(titleKey);
    message.textContent = this.t(messageKey);
    message.style.whiteSpace = promotionStep ? "pre-line" : "";
    this.panel.querySelector('[data-role="explanation"]').textContent = promotionStep ? "" : (this.dynamicMessage || "");
    this.panel.querySelector('[data-role="auto-label"]').textContent = this.t("auto");
    this.panel.querySelector('[data-action="auto"]').checked = this.progress.autoExplain;
    for (const action of ["previous", "next", "why", "repeat"]) {
      this.panel.querySelector(`[data-action="${action}"]`).textContent = this.t(action);
    }
    this.panel.querySelector('[data-action="previous"]').disabled = this.progress.step === 0;
    this.panel.querySelector('[data-action="next"]').disabled = this.progress.step === STEPS.length - 1;
    this.panel.querySelector('[data-action="why"]').hidden = promotionStep;
    this.panel.querySelector('[data-action="repeat"]').hidden = promotionStep;
    this.panel.querySelector('[data-action="close"]').setAttribute("aria-label", this.t("close"));
    this.panel.dataset.step = String(this.progress.step);
    this.panel.dataset.selected = state.selectedPieceId || "";
  }

  dispose() {
    window.clearInterval(this.levelTourTimer);
    this.panel.remove();
  }
}
