import * as THREE from "three";
import { pieceCellEnvelope } from "./pieceScaleProfile.js";

export const OPEN_SOURCE_STAUNTON_V14_REVISION = "2026-09-01-open-source-staunton-v14-carved-polyhedral";
export const OPEN_SOURCE_STAUNTON_V14_SOURCE_ID = "open-source-staunton-v14-carved-polyhedral";
const SOURCE_ID = OPEN_SOURCE_STAUNTON_V14_SOURCE_ID;
const TYPES = ["pawn", "rook", "knight", "bishop", "queen", "king"];
const LATHE_SEGMENTS = 112;
const texCache = new Map();
const matCache = new Map();
const templateCache = new Map();

function noise(x, y, seed) { let n=(x*374761393+y*668265263+seed*69069)|0; n=Math.imul(n^(n>>>13),1274126177); return ((n^(n>>>16))>>>0)/4294967295; }
function makeTexture(type, side) { const key=`${type}:${side}`; if(texCache.has(key)) return texCache.get(key); const size=128,data=new Uint8Array(size*size*4),role=TYPES.indexOf(type)+1; for(let y=0;y<size;y++){for(let x=0;x<size;x++){const i=(y*size+x)*4,n=noise(x,y,role*97+(side==="white"?11:43)),vein=Math.pow(Math.max(0,Math.sin(x*.073+y*.091+n*3)),20),cut=Math.pow(Math.max(0,Math.cos((x+y)*(.055+role*.003))),28); if(side==="white"){const b=224+Math.round(n*17);data[i]=Math.min(255,b+vein*15);data[i+1]=Math.min(255,b+vein*9);data[i+2]=Math.min(255,b-5+cut*12);}else{const b=100+Math.round(n*35);data[i]=Math.min(255,b-14+vein*8);data[i+1]=Math.min(255,b+vein*16+cut*4);data[i+2]=Math.min(255,b+14+vein*22+cut*9);}data[i+3]=255;}} const t=new THREE.DataTexture(data,size,size,THREE.RGBAFormat); t.needsUpdate=true;t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(3,3);t.userData={roleTexture:true,type,side,width:size,height:size};texCache.set(key,t);return t; }
function mats(type,side){const key=`${type}:${side}`;if(matCache.has(key))return matCache.get(key);const white=side==="white",map=makeTexture(type,side);const body=new THREE.MeshPhysicalMaterial({color:white?0xf0ece3:0x52677c,map,bumpMap:map,bumpScale:white?.018:.014,roughness:white?.27:.24,metalness:white?.10:.28,clearcoat:.88,clearcoatRoughness:.12,envMapIntensity:white?1.35:1.65,emissive:white?0x000000:0x07121d,emissiveIntensity:white?0:.16}),trim=new THREE.MeshPhysicalMaterial({color:white?0xcaa65b:0x18c9bf,metalness:.82,roughness:.13,clearcoat:.9,emissive:white?0x281a09:0x043b37,emissiveIntensity:white?.04:.18}),dark=new THREE.MeshPhysicalMaterial({color:white?0x294b5d:0x071219,metalness:.45,roughness:.18,clearcoat:.72}),eye=new THREE.MeshPhysicalMaterial({color:white?0x163b55:0xd6aa61,metalness:.45,roughness:.1,clearcoat:.98});const out={body,trim,dark,eye};matCache.set(key,out);return out;}
function mark(o,role){o.castShadow=true;o.receiveShadow=true;o.userData.openSourceStauntonRole=role;o.userData.forgePremiumRole=role;return o;} function mesh(g,m,r){return mark(new THREE.Mesh(g,m),r);} function lathe(p,m,r){return mesh(new THREE.LatheGeometry(p.map(([x,y])=>new THREE.Vector2(x,y)),LATHE_SEGMENTS),m,r);} function ring(g,m,r,y,t,role){const q=mesh(new THREE.TorusGeometry(r,t,14,80),m,role);q.rotation.x=Math.PI/2;q.position.y=y;g.add(q);} function extrude(s,d,m,r,b=.018,bs=5){const geo=new THREE.ExtrudeGeometry(s,{depth:d,steps:2,bevelEnabled:true,bevelSize:b,bevelThickness:b,bevelSegments:bs,curveSegments:32});geo.center();return mesh(geo,m,r);} function panel(g,m,y,r,w,h,d,role,rot=0){const s=new THREE.Shape();s.moveTo(-w/2,-h/2);s.lineTo(w/2,-h/2);s.lineTo(w*.42,h/2);s.lineTo(-w*.42,h/2);s.closePath();const p=extrude(s,d,m,role,Math.min(w,h)*.05,3);p.position.set(Math.cos(rot)*r,y,Math.sin(rot)*r);p.rotation.y=Math.PI/2-rot;g.add(p);} function base(g,m,sc=1){g.add(lathe([[0,0],[.20*sc,0],[.34*sc,.008],[.46*sc,.03],[.52*sc,.065],[.515*sc,.105],[.48*sc,.145],[.42*sc,.20],[.37*sc,.255],[.35*sc,.30]],m.body,"base-sculpt"));ring(g,m.trim,.485*sc,.10,.012,"base-engraved-ring");ring(g,m.dark,.392*sc,.215,.008,"base-deboss-groove");for(let i=0;i<8;i++)panel(g,m.dark,.19,.405*sc,.085,.095,.012,"base-engraved-panel",i*Math.PI/4);} function collar(g,m,r,y){const c=mesh(new THREE.CylinderGeometry(r,r*.9,.064,80,2),m.body,"collar");c.position.y=y;g.add(c);ring(g,m.trim,r*.97,y+.02,.009,"collar-inlay");} function gem(g,m,x,y,z,s=1,role="gem"){const q=mesh(new THREE.OctahedronGeometry(.04*s,1),m.trim,role);q.position.set(x,y,z);q.scale.set(.82,1.35,.82);g.add(q);} function fit(content,type){const e=pieceCellEnvelope(type);content.position.set(0,0,0);content.scale.setScalar(1);content.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(content),sz=b.getSize(new THREE.Vector3());if(![sz.x,sz.y,sz.z].every(v=>Number.isFinite(v)&&v>0))throw new Error(`Invalid ${type} bounds`);const s=Math.min(e.maxHeight/sz.y,e.maxFootprint/sz.x,e.maxFootprint/sz.z);content.scale.setScalar(s);content.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(content);const c=b.getCenter(new THREE.Vector3());content.position.x-=c.x;content.position.z-=c.z;content.position.y-=b.min.y;content.updateMatrixWorld(true);const root=new THREE.Group();root.name=`${type}-open-source-staunton-v14`;root.add(content);return root;}
function pawn(m){const g=new THREE.Group();base(g,m,.76);g.add(lathe([[.24,.29],[.205,.37],[.17,.51],[.155,.68],[.165,.80],[.19,.88],[.21,.92]],m.body,"pawn-carved-stem"));collar(g,m,.205,.95);const h=mesh(new THREE.IcosahedronGeometry(.19,4),m.body,"pawn-faceted-head");h.position.y=1.18;g.add(h);gem(g,m,0,1.36,0,.48,"pawn-crown-inlay");return g;}
function rook(m){const g=new THREE.Group();base(g,m,.84);g.add(lathe([[.29,.29],[.25,.37],[.21,.52],[.19,.72],[.20,.89],[.24,1.02],[.28,1.10]],m.body,"rook-carved-tower"));for(let i=0;i<8;i++)panel(g,m.dark,.72,.205,.082,.31,.018,"rook-vertical-engraving",i*Math.PI/4);collar(g,m,.30,1.13);const crown=mesh(new THREE.CylinderGeometry(.34,.31,.16,16,2),m.body,"rook-crown");crown.position.y=1.27;g.add(crown);const recess=mesh(new THREE.CylinderGeometry(.225,.225,.07,64,1),m.dark,"rook-recess-cut");recess.position.y=1.36;g.add(recess);const s=new THREE.Shape();s.moveTo(-.06,-.085);s.lineTo(.06,-.085);s.lineTo(.06,.085);s.lineTo(-.06,.085);s.closePath();for(let i=0;i<8;i++){const a=i*Math.PI/4,b=extrude(s,.11,m.body,"rook-battlement",.01,3);b.position.set(Math.cos(a)*.28,1.44,Math.sin(a)*.28);b.rotation.y=Math.PI/2-a;g.add(b);}return g;}
function knightProfile(){const s=new THREE.Shape();s.moveTo(-.22,.02);s.bezierCurveTo(-.32,.20,-.30,.48,-.18,.68);s.bezierCurveTo(-.10,.82,-.08,1.04,.02,1.18);s.bezierCurveTo(.12,1.32,.29,1.39,.44,1.33);s.bezierCurveTo(.56,1.28,.62,1.16,.58,1.08);s.bezierCurveTo(.54,1.00,.42,.98,.34,.91);s.bezierCurveTo(.27,.84,.22,.73,.19,.62);s.bezierCurveTo(.15,.45,.14,.25,.14,.08);s.bezierCurveTo(.05,-.01,-.10,-.04,-.22,.02);s.closePath();const cut=new THREE.Path();cut.absellipse(.20,.95,.10,.055,0,Math.PI*2,false,0);s.holes.push(cut);return s;} function maneProfile(){const s=new THREE.Shape();s.moveTo(-.17,.12);[[-.30,.28],[-.22,.36],[-.34,.45],[-.23,.53],[-.35,.63],[-.22,.72],[-.30,.83],[-.17,.91],[-.21,1.04],[-.07,1.01]].forEach(p=>s.lineTo(...p));s.bezierCurveTo(-.02,.78,-.02,.48,-.05,.18);s.closePath();return s;}
function knight(m){const g=new THREE.Group();base(g,m,.88);g.add(lathe([[.30,.29],[.285,.33],[.255,.38],[.235,.43]],m.body,"knight-base-support"));collar(g,m,.31,.43);const body=extrude(knightProfile(),.30,m.body,"knight-sculpt",.026,8);body.position.set(-.03,1.12,-.15);g.add(body);const jaw=new THREE.Shape();jaw.moveTo(-.04,-.03);jaw.bezierCurveTo(.09,-.07,.27,-.03,.35,.05);jaw.bezierCurveTo(.25,.12,.08,.13,-.05,.07);jaw.closePath();const jm=extrude(jaw,.23,m.body,"knight-jaw",.015,5);jm.position.set(.32,1.38,-.115);g.add(jm);const mane=extrude(maneProfile(),.085,m.trim,"knight-mane",.010,4);mane.position.set(-.19,1.01,-.043);g.add(mane);for(const z of[-.14,.14]){const ear=mesh(new THREE.ConeGeometry(.045,.18,8,2),m.body,"knight-ear");ear.position.set(.08,1.77,z);ear.rotation.z=-.15;g.add(ear);}for(const z of[-.16,.16]){const eye=mesh(new THREE.SphereGeometry(.028,16,12),m.eye,"knight-eye");eye.position.set(.33,1.56,z);g.add(eye);}const nost=mesh(new THREE.SphereGeometry(.018,12,8),m.dark,"knight-nostril");nost.position.set(.59,1.43,.16);g.add(nost);panel(g,m.dark,1.22,.165,.11,.24,.016,"knight-cheek-engraving",0);return g;}
function bishopMitre(sign=1){const s=new THREE.Shape();s.moveTo(0,-.35);s.bezierCurveTo(.20*sign,-.22,.27*sign,.06,.18*sign,.30);s.bezierCurveTo(.13*sign,.43,.06*sign,.54,0,.64);s.lineTo(0,-.35);s.closePath();return s;} function bishop(m){const g=new THREE.Group();base(g,m,.82);g.add(lathe([[.27,.29],[.235,.40],[.19,.58],[.17,.78],[.18,.96],[.22,1.08]],m.body,"bishop-carved-body"));for(let i=0;i<6;i++)panel(g,m.dark,.72,.18,.065,.34,.014,"bishop-body-engraving",i*Math.PI/3);collar(g,m,.235,1.10);const l=extrude(bishopMitre(-1),.22,m.body,"bishop-mitre-left",.02,6);l.position.set(-.015,1.42,-.11);g.add(l);const r=extrude(bishopMitre(1),.22,m.body,"bishop-mitre-right",.02,6);r.position.set(.015,1.42,-.11);g.add(r);const slit=new THREE.Shape();slit.moveTo(-.017,-.19);slit.lineTo(.017,-.19);slit.lineTo(.017,.19);slit.lineTo(-.017,.19);slit.closePath();const sm=extrude(slit,.012,m.dark,"bishop-slit",.003,2);sm.position.set(.025,1.59,.008);sm.rotation.z=-.48;g.add(sm);gem(g,m,0,1.94,0,.55,"bishop-gem");return g;}
function queen(m){const g=new THREE.Group();base(g,m,.86);g.add(lathe([[.29,.29],[.25,.39],[.205,.58],[.18,.82],[.19,1.02],[.24,1.18]],m.body,"queen-carved-body"));for(let i=0;i<8;i++)panel(g,m.dark,.80,.19,.055,.40,.012,"queen-engraved-flute",i*Math.PI/4);collar(g,m,.255,1.20);for(let i=0;i<8;i++){const a=i*Math.PI/4,s=new THREE.Shape();s.moveTo(-.055,-.08);s.bezierCurveTo(-.06,.05,-.03,.22,0,.34);s.bezierCurveTo(.03,.22,.06,.05,.055,-.08);s.closePath();const p=extrude(s,.10,m.body,"queen-crown-point",.012,4);p.position.set(Math.cos(a)*.235,1.47,Math.sin(a)*.235);p.rotation.y=Math.PI/2-a;g.add(p);gem(g,m,Math.cos(a)*.235,1.79,Math.sin(a)*.235,.42,"queen-gem");}gem(g,m,0,1.66,0,.68,"queen-center-gem");return g;}
function king(m){const g=new THREE.Group();base(g,m,.90);g.add(lathe([[.31,.29],[.27,.40],[.22,.60],[.19,.84],[.20,1.05],[.25,1.20]],m.body,"king-carved-body"));for(let i=0;i<8;i++)panel(g,m.dark,.84,.20,.065,.42,.013,"king-engraved-flute",i*Math.PI/4);collar(g,m,.27,1.23);const stem=mesh(new THREE.CylinderGeometry(.064,.09,.20,48,2),m.body,"king-crown-support");stem.position.y=1.35;g.add(stem);const orb=mesh(new THREE.IcosahedronGeometry(.12,3),m.trim,"king-orb");orb.position.y=1.48;g.add(orb);const s=new THREE.Shape();s.moveTo(-.055,-.25);s.lineTo(.055,-.25);s.lineTo(.055,-.07);s.lineTo(.23,-.07);s.lineTo(.23,.05);s.lineTo(.055,.05);s.lineTo(.055,.28);s.lineTo(-.055,.28);s.lineTo(-.055,.05);s.lineTo(-.23,.05);s.lineTo(-.23,-.07);s.lineTo(-.055,-.07);s.closePath();const cross=extrude(s,.10,m.body,"king-cross",.014,4);cross.position.set(0,1.80,-.05);g.add(cross);const inlay=extrude(s,.018,m.trim,"king-cross-inlay",.004,2);inlay.scale.set(.72,.72,.72);inlay.position.set(0,1.80,.051);g.add(inlay);return g;}
const builders={pawn,rook,knight,bishop,queen,king}; export function countObjectTriangles(o){let n=0;o.traverse(c=>{if(!c.geometry)return;const g=c.geometry;n+=g.index?g.index.count/3:g.attributes?.position?.count/3;});return Math.round(n);} export function countUniquePieceResources(o){const gs=new Set(),ms=new Set(),ts=new Set();o.traverse(c=>{if(c.geometry)gs.add(c.geometry.uuid);const arr=Array.isArray(c.material)?c.material:[c.material];for(const m of arr){if(!m)continue;ms.add(m.uuid);for(const k of["map","bumpMap","roughnessMap","normalMap"])if(m[k])ts.add(m[k].uuid);}});return{meshes:gs.size,uniqueGeometries:gs.size,uniqueMaterials:ms.size,uniqueTextures:ts.size};}
function makeTemplate(type,side){const root=fit(builders[type](mats(type,side)),type);root.userData={forgeVisualSource:SOURCE_ID,runtimePrimarySource:SOURCE_ID,referenceAssetsPolicy:"reference-only-not-runtime",freeForPublicRenderer:true,type,side};root.traverse(child=>{if(child.geometry)child.geometry.userData={...child.geometry.userData,forgeSharedPieceGeometry:true};});return root;}
function cloneTemplate(template){const object=template.clone(true),materialClones=new Map();object.traverse(child=>{if(!child.material)return;const cloneMaterial=(material)=>{if(!materialClones.has(material)){const clone=material.clone();clone.userData={...clone.userData,forgePieceInstanceMaterial:true};materialClones.set(material,clone);}return materialClones.get(material);};child.material=Array.isArray(child.material)?child.material.map(cloneMaterial):cloneMaterial(child.material);});object.userData={...template.userData};return object;}
export class OpenSourceStauntonV14PieceSet{create(type,side="white"){const t=TYPES.includes(type)?type:"pawn",s=side==="black"?"black":"white",key=`${t}:${s}`;if(!templateCache.has(key))templateCache.set(key,makeTemplate(t,s));return cloneTemplate(templateCache.get(key));}inspect(type,side="white"){const o=this.create(type,side),b=new THREE.Box3().setFromObject(o),s=b.getSize(new THREE.Vector3()),e=pieceCellEnvelope(type);return{type,side,triangles:countObjectTriangles(o),width:s.x,height:s.y,depth:s.z,bounds:{x:s.x,y:s.y,z:s.z},finite:[s.x,s.y,s.z].every(Number.isFinite),fitsCell:s.x<=e.maxFootprint+1e-6&&s.z<=e.maxFootprint+1e-6,fitsLevel:s.y<=e.maxHeight+1e-6,runtimePrimarySource:SOURCE_ID,referenceAssetsPolicy:"reference-only-not-runtime",freeForPublicRenderer:true,resources:countUniquePieceResources(o)};}inspectAll(){return TYPES.map(t=>this.inspect(t,"white"));}}
export function getRoleTextureV14(type,side){return makeTexture(type,side);}
